name: Access Challenge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  access_challenge:
    runs-on: ubuntu-latest
    steps:
      - name: Make request with custom headers
        run: |
          curl -v -H "User-Agent: GitHubActions" -H "Accept: application/json" "https://actions.ctf.cert.unlp.edu.ar/"
